#!/bin/bash

#Обновляем репозитории
sudo apt update -y

#Устанавливаем Node.js
sudo apt-get install -y ca-certificates curl gnupg
sudo mkdir -p /etc/apt/keyrings
curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
NODE_MAJOR=20
echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list
sudo apt-get update
sudo apt-get install nodejs -y

#Устанавливаем Nginx
sudo apt install -y nginx
sudo apt install unzip
curl -fsSL https://bun.sh/install | bash

#Устанавливаем Yarn и PM2
npm i -g pm2

#Устанавливаем все для SSL
sudo apt update
sudo snap install --classic certbot
sudo ln -s /snap/bin/certbot /usr/bin/certbot

#Обновляем правила ufw
sudo ufw allow 'Nginx Full'
sudo ufw delete allow 'Nginx HTTP'

#Включаем FireWall
sudo ufw enable -y
sudo ufw allow 22

#Создаем файл подкачки
sudo fallocate -l 1G /swapfile
sudo chmod 600 /swapfile
sudo mkswap /swapfile
sudo swapon /swapfile
echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab
