#!/bin/bash

#Обновляем репозитории
sudo apt update -y

#Устанавливаем Node.js
# Download and install nvm:
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash
# in lieu of restarting the shell
\. "$HOME/.nvm/nvm.sh"
# Download and install Node.js:
nvm install 22
# Verify the Node.js version:
node -v # Should print "v22.20.0".
# Verify npm version:
npm -v # Should print "10.9.3".

#Устанавливаем Nginx
sudo apt install -y nginx
sudo apt install unzip
curl -fsSL https://bun.sh/install | bash

# Redis
sudo apt install redis-server

#Устанавливаем Yarn и PM2
npm i -g pm2

#Устанавливаем ffmpeg
apt install ffmpeg -y

#Устанавливаем все для SSL
sudo apt update
sudo snap install --classic certbot
sudo ln -s /snap/bin/certbot /usr/bin/certbot

#Обновляем правила ufw
sudo ufw allow 'Nginx Full'
sudo ufw delete allow 'Nginx HTTP'

#Включаем FireWall
sudo ufw enable -y
sudo ufw allow 22

#Создаем файл подкачки
sudo fallocate -l 1G /swapfile
sudo chmod 600 /swapfile
sudo mkswap /swapfile
sudo swapon /swapfile
echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab
