#!/bin/bash

#Обновляем репозитории
sudo apt update -y
sudo apt upgrade -y

#Устанавливаем curl
sudo apt install -y curl

#Устанавливаем Node.js
curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
sudo apt-get install -y nodejs

#Устанавливаем Nginx
sudo apt install -y nginx

#Устанавливаем Yarn и PM2
npm i -g yarn
npm i -g pm2

#Добавляем репозитории для CertBot
sudo apt install -y software-properties-common
sudo add-apt-repository ppa:certbot/certbot

#Устанавливаем все для SSL
sudo apt update
sudo apt install -y python-certbot-nginx

#Обновляем правила ufw
sudo ufw allow 'Nginx Full'
sudo ufw delete allow 'Nginx HTTP'

#Включаем FireWall
sudo ufw enable -y
sudo ufw allow 22

#Создаем файл подкачки
sudo fallocate -l 1G /swapfile
sudo chmod 600 /swapfile
sudo mkswap /swapfile
sudo swapon /swapfile
echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab